import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import ButtonOne from '@/components/buttonOne'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1><Link href='/pageone'>To Page 1</Link></h1>
      <h1><Link href='/pageTwo'>To Page 2</Link></h1>
      <ButtonOne />
      <Image src="/paint_svc.jpeg" width="400" height="400" alt="paint" />
      </main>
    </>
  )
}
